--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20-Mar-21 9:00:43 AM
-- Server version: 5.5.5-10.4.18-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE misa_eshop_develop;

--
-- Drop procedure `Proc_DeleteProductChildres`
--
DROP PROCEDURE IF EXISTS Proc_DeleteProductChildres;

--
-- Drop procedure `Proc_DeleteProductParent`
--
DROP PROCEDURE IF EXISTS Proc_DeleteProductParent;

--
-- Drop procedure `Proc_GenProductSKU`
--
DROP PROCEDURE IF EXISTS Proc_GenProductSKU;

--
-- Drop procedure `Proc_GetAllProductChildren`
--
DROP PROCEDURE IF EXISTS Proc_GetAllProductChildren;

--
-- Drop procedure `Proc_GetAllProductParent`
--
DROP PROCEDURE IF EXISTS Proc_GetAllProductParent;

--
-- Drop procedure `Proc_GetLength`
--
DROP PROCEDURE IF EXISTS Proc_GetLength;

--
-- Drop procedure `Proc_GetNumberOfRowProduct`
--
DROP PROCEDURE IF EXISTS Proc_GetNumberOfRowProduct;

--
-- Drop procedure `Proc_InsertProduct`
--
DROP PROCEDURE IF EXISTS Proc_InsertProduct;

--
-- Drop function `Func_GetPath`
--
DROP FUNCTION IF EXISTS Func_GetPath;

--
-- Drop procedure `Proc_GetPath`
--
DROP PROCEDURE IF EXISTS Proc_GetPath;

--
-- Drop procedure `Proc_GetProductByID`
--
DROP PROCEDURE IF EXISTS Proc_GetProductByID;

--
-- Drop procedure `Proc_GetProductBySKU`
--
DROP PROCEDURE IF EXISTS Proc_GetProductBySKU;

--
-- Drop procedure `Proc_GetProductPaging`
--
DROP PROCEDURE IF EXISTS Proc_GetProductPaging;

--
-- Drop procedure `Proc_UpdateProduct`
--
DROP PROCEDURE IF EXISTS Proc_UpdateProduct;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Set default database
--
USE misa_eshop_develop;

--
-- Create table `product`
--
CREATE TABLE product (
  ProductID char(36) NOT NULL COMMENT 'Khóa chính',
  ProductName varchar(255) NOT NULL COMMENT 'Tên hàng hóa',
  SKU varchar(255) DEFAULT NULL COMMENT 'Mã hàng hóa',
  Status int(2) DEFAULT NULL COMMENT 'Trạng thái bán hàng 1- đang kinh doanh, 0-ngừng kinh doanh',
  CategoryCode int(11) DEFAULT NULL COMMENT 'Mã nhóm hàng hóa( từ 1-11)',
  BuyPrice double DEFAULT NULL COMMENT 'Giá mua',
  SellPrice double DEFAULT NULL COMMENT 'Giá bán',
  UnitCode int(11) DEFAULT NULL COMMENT 'Mã đơn vị (1- đôi, 2- chiếc, 3- túi, 4- kg, 5- thùng, 6-met, 7- cuộn, 8-lit)',
  IsShow int(2) DEFAULT NULL COMMENT 'Hiển thị trên màn hình bán hàng 1 - có hiển thị, 0- không hiển thị',
  Description varchar(4000) DEFAULT NULL COMMENT 'Mô tả',
  Image varchar(255) DEFAULT NULL,
  Color varchar(255) DEFAULT NULL COMMENT 'Màu sắc',
  Barcode int(11) DEFAULT NULL COMMENT 'mã vạch',
  FullPath varchar(255) DEFAULT NULL,
  ProductIDParent char(36) NOT NULL DEFAULT '' COMMENT 'ID của hàng hóa cha',
  CreatedBy varchar(255) DEFAULT 'vtt',
  CreatedDate datetime DEFAULT CURRENT_TIMESTAMP() COMMENT 'Ngày tạo',
  ModifiedDate datetime DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ProductID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1445,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `Barcode` on table `product`
--
ALTER TABLE product
ADD UNIQUE INDEX Barcode (Barcode);

DELIMITER $$

--
-- Create procedure `Proc_UpdateProduct`
--
CREATE PROCEDURE Proc_UpdateProduct (IN productID char(36), IN productName varchar(255), IN sku varchar(255), IN status int(2), IN categoryCode int(2), IN buyPrice double, IN sellPrice double, IN unitCode int(11), IN isShow int(2), IN description mediumtext, IN image mediumtext, IN barCode int(11), IN color varchar(255), IN modifiedDate datetime)
SQL SECURITY INVOKER
COMMENT 'Proc chỉnh sửa thông tin hàng hóa'
BEGIN
  UPDATE product p
  SET p.ProductName = productName,
      p.SKU = sku,
      p.Status = status,
      p.CategoryCode = categoryCode,
      p.BuyPrice = buyPrice,
      p.SellPrice = sellPrice,
      p.UnitCode = unitCode,
      p.IsShow = isShow,
      p.Description = description,
      p.Image = image,
      p.ModifiedDate = NOW()

  WHERE p.ProductID = productID;
END
$$

--
-- Create procedure `Proc_GetProductPaging`
--
CREATE PROCEDURE Proc_GetProductPaging (IN `limit` int, IN offset int, IN productName varchar(255), IN productSKU varchar(255), IN categoryCode int(11), IN unitCode int(2), IN sellPrice double, IN isShow int(2), IN status int(2))
SQL SECURITY INVOKER
COMMENT 'proc lấy phân trang kèm tìm kiếm'
BEGIN
  SET productName = CASE WHEN productName IS NULL THEN '' ELSE productName END;
  SET productSKU = CASE WHEN productSKU IS NULL THEN '' ELSE productSKU END;

  SELECT
    *
  FROM product p
  WHERE p.ProductName LIKE CONCAT('%', productName, '%')
  AND p.SKU LIKE CONCAT('%', productSKU, '%')
  AND (CASE WHEN status IN (0, 1) THEN (p.Status = status) ELSE (TRUE) END)
  AND (CASE WHEN isShow IN (0, 1) THEN (p.IsShow = isShow) ELSE (TRUE) END)
  AND (CASE WHEN sellPrice > 0 THEN (p.SellPrice >= sellPrice) ELSE (TRUE) END)
  AND (CASE WHEN categoryCode > 0 THEN (p.CategoryCode = categoryCode) ELSE (TRUE) END)
  AND (CASE WHEN unitCode > 0 THEN (p.UnitCode = unitCode) ELSE (TRUE) END)
  ORDER BY p.SKU DESC
  LIMIT `offset`, `limit`;

END
$$

--
-- Create procedure `Proc_GetProductBySKU`
--
CREATE PROCEDURE Proc_GetProductBySKU (IN SKU varchar(255))
SQL SECURITY INVOKER
COMMENT 'Lấy cửa hàng theo mã SKU'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.SKU = SKU;
END
$$

--
-- Create procedure `Proc_GetProductByID`
--
CREATE PROCEDURE Proc_GetProductByID (IN id char(36))
SQL SECURITY INVOKER
COMMENT 'Proc Lấy hàng hóa theo id'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.ProductID = id;
END
$$

--
-- Create procedure `Proc_GetPath`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_GetPath (IN cat_id char(36), OUT path text)
BEGIN
  DECLARE catname varchar(1000);/*tên để nối*/
  DECLARE temppath text;/*đường dẫn tên rỗng*/
  DECLARE tempparent char(36);/*id cha rỗng*/
  SET max_sp_recursion_depth = 4000;/*max nhập*/
  SELECT
    p.ProductName,
    p.ProductIDParent
  FROM product p
  WHERE p.ProductID = cat_id INTO catname, tempparent;/*catname = name, tempparent = parent*/
  IF tempparent IS NULL/*Nếu tempparent null*/
  THEN
    SET path = catname;/* thì đường dẫn bằng catname tức tên cha to nhất*/
  ELSE/* Nếu như có cha, thức thằng catname đang chọn là con*/
    CALL Proc_GetPath(tempparent, temppath);/*đệ quy gọi lại với tempparent và path rỗng mới*/
    SET path = CONCAT(temppath, '/ ', catname);/* đường dẫn bằng nối đường dẫn cũ/tên thằng mới*/
  END IF;
END
$$

--
-- Create function `Func_GetPath`
--
CREATE DEFINER = 'root'@'localhost'
FUNCTION Func_GetPath (cat_id char(36))
RETURNS text CHARSET utf8
DETERMINISTIC
BEGIN
  DECLARE res text;
  CALL Proc_GetPath(cat_id, res);/*gọi proceduce*/
  RETURN res;
END
$$

--
-- Create procedure `Proc_InsertProduct`
--
CREATE PROCEDURE Proc_InsertProduct (IN productID char(36), IN productName varchar(255), IN sku varchar(255), IN status int(2), IN categoryCode int(2), IN buyPrice double, IN sellPrice double, IN unitCode int(11), IN isShow int(2), IN description mediumtext, IN image mediumtext, IN barCode int(11), IN color varchar(255), IN modifiedDate datetime, IN productIDParent char(36))
SQL SECURITY INVOKER
COMMENT 'Proc thêm mới hàng hóa'
BEGIN
  DECLARE fullPath varchar(255);

  INSERT INTO product (ProductID, ProductName, SKU, Status, CategoryCode, BuyPrice, SellPrice, UnitCode, IsShow, Description, Image, CreatedDate, CreatedBy, ModifiedDate, ProductIDParent, Color, Barcode, FullPath)
    VALUES (productID, productName, sku, status, categoryCode, buyPrice, sellPrice, unitCode, isShow, description, image, NOW(), 'vtt', NOW(), productIDParent, color, barCode, fullPath);
  SET fullPath = Func_GetPath(productID);
  UPDATE product p
  SET p.FullPath = Func_GetPath(productID)
  WHERE p.ProductID = productID;
END
$$

--
-- Create procedure `Proc_GetNumberOfRowProduct`
--
CREATE PROCEDURE Proc_GetNumberOfRowProduct ()
SQL SECURITY INVOKER
COMMENT 'Lấy số lượng bản ghi của bảng Product'
BEGIN
  SELECT
    COUNT(*)
  FROM product p;
END
$$

--
-- Create procedure `Proc_GetLength`
--
CREATE PROCEDURE Proc_GetLength (IN productName varchar(255), IN productSKU varchar(255), IN categoryCode int(11), IN unitCode int(2), IN sellPrice double, IN isShow int(2), IN status int(2))
SQL SECURITY INVOKER
COMMENT 'Proc lấy số bản ghi '
BEGIN
  SET productName = CASE WHEN productName IS NULL THEN '' ELSE productName END;
  SET productSKU = CASE WHEN productSKU IS NULL THEN '' ELSE productSKU END;

  SELECT
    COUNT(*) AS NumberOfRecord
  FROM product p
  WHERE p.ProductName LIKE CONCAT('%', productName, '%')
  AND p.SKU LIKE CONCAT('%', productSKU, '%')
  AND (CASE WHEN status IN (0, 1) THEN (p.Status = status) ELSE (TRUE) END)
  AND (CASE WHEN isShow IN (0, 1) THEN (p.IsShow = isShow) ELSE (TRUE) END)
  AND (CASE WHEN sellPrice > 0 THEN (p.SellPrice >= sellPrice) ELSE (TRUE) END)
  AND (CASE WHEN categoryCode > 0 THEN (p.CategoryCode = categoryCode) ELSE (TRUE) END)
  AND (CASE WHEN unitCode > 0 THEN (p.UnitCode = unitCode) ELSE (TRUE) END);
END
$$

--
-- Create procedure `Proc_GetAllProductParent`
--
CREATE PROCEDURE Proc_GetAllProductParent ()
SQL SECURITY INVOKER
COMMENT 'Proc lấy hàng hóa cha'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.ProductIDParent = '00000000-0000-0000-0000-000000000000';
END
$$

--
-- Create procedure `Proc_GetAllProductChildren`
--
CREATE PROCEDURE Proc_GetAllProductChildren (IN id char(36))
SQL SECURITY INVOKER
COMMENT 'proc lấy hàng hóa con ở bảng chi tiết thuộc tính'
BEGIN
  SELECT
    *
  FROM product p
  WHERE p.ProductIDParent = id;
END
$$

--
-- Create procedure `Proc_GenProductSKU`
--
CREATE PROCEDURE Proc_GenProductSKU (IN productKey varchar(255))
SQL SECURITY INVOKER
COMMENT 'Tạo mới mã sku cho sản phẩm'
BEGIN
  DECLARE productSkuCode varchar(255);
  DECLARE codeNumber int(11);

  SELECT
    p.SKU INTO productSkuCode
  FROM product p
  WHERE p.SKU LIKE CONCAT(productKey, '%')
  AND CAST(SUBSTR(p.SKU, LENGTH(productKey) + 1) AS int) > 0
  ORDER BY p.SKU DESC
  LIMIT 1;

  SET codeNumber = CASE WHEN productSkuCode IS NULL THEN 1 ELSE CAST(SUBSTR(productSkuCode, LENGTH(productKey) + 1) AS int) + 1 END;

  SELECT
    CONCAT(productKey, codeNumber);

END
$$

--
-- Create procedure `Proc_DeleteProductParent`
--
CREATE PROCEDURE Proc_DeleteProductParent (IN id char(36))
SQL SECURITY INVOKER
COMMENT 'Proc xóa hàng hóa cha ở bảng chính'
BEGIN
  DELETE
    FROM product
  WHERE ProductID = id
    OR ProductIDParent = id;
END
$$

--
-- Create procedure `Proc_DeleteProductChildres`
--
CREATE PROCEDURE Proc_DeleteProductChildres (IN id char(36))
SQL SECURITY INVOKER
COMMENT 'Proc xóa hàng hóa con nằm trong bảng detail'
BEGIN
  DELETE
    FROM product
  WHERE ProductIDParent = id;
END
$$

DELIMITER ;

-- 
-- Dumping data for table product
--
INSERT INTO product VALUES
('0f8cfd75-6742-4487-9c94-7b267ab96297', 'Xe máy Honda', 'XMH1', 1, 14, 90000000, 150000000, 1, 1, 'Xe máy đắt tiền cho nhà giàu', 'link:///', 'Đỏ', 17021041, NULL, '7623d42f-35f4-1ce5-987d-e8c757976496', 'vtt', '2021-03-18 10:34:16', '2021-03-18 10:34:16'),
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Hoa quả ', 'HQ1', 0, 9, 158534816, 341711721, 3, 1, 'A reprehenderit expedita officia consequatur. A autem molestias tempore qui.\r\nBlanditiis quos non error dignissimos. Modi sequi maiores nihil dolores. Voluptatem porro sit quia error. Animi delectus tenetur consequatur libero! Consequatur sit totam nihil quae. Possimus et aut sint sed? Autem qui sit ad nesciunt; nulla natus quos consequatur aliquam.\r\n', '102E0EV1F47A95B5BNIL10U9M517OUT7P4O59X7M', NULL, 307297987, 'Hoa quả ', '00000000-0000-0000-0000-000000000000', 'Adolph Francisco', '2000-12-28 15:52:12', '1984-09-12 19:02:56'),
('11f7089b-33e6-371a-f817-7000f455f3d5', 'Giày ', 'G1', 1, 4, 862948515, 469947961, 2, 0, 'Vero totam inventore distinctio sunt. Dolorem voluptatem molestias non nostrum. Velit voluptatem distinctio delectus dolorem. Laborum quos ipsam ut provident. Atque esse omnis et repellat.\r\nAsperiores beatae unde illo voluptatem. In tempora sequi et sint! Eum voluptatem ut nemo illo. Dolorem atque ipsum explicabo dolore! Asperiores rem qui accusantium fuga.\r\n', 'FF3K860BJXL8', '0', 1632497363, 'Giày ', '00000000-0000-0000-0000-000000000000', 'Kasey Furr', '2002-09-29 02:55:38', '1976-05-12 14:39:22'),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nước ngọt ', 'NN1', 0, 11, 432, 200000, 4, 1, 'Enim ullam fugiat sunt et dolore molestiae omnis nihil sit atque aliquid nobis necessitatibus a.', 'WCC04WA7S7', NULL, 2147483647, 'Nước ngọt ', '00000000-0000-0000-0000-000000000000', 'Letha Bolt', '1999-01-01 00:07:13', '1970-01-01 00:00:04'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'Đồ gia dụng', 'DGD1', 0, 2, 791135855, 118561606, 1, 1, 'Ipsa sint fugit fuga soluta; aut dolorem at rerum qui impedit; dolor qui cupiditate, expedita quia inventore veniam architecto voluptatem nihil culpa dolorem qui recusandae.\r\nDolorem alias sit et quae, ut natus accusantium omnis exercitationem enim corporis qui omnis. Officia veritatis, consectetur repellendus nisi incidunt debitis omnis quia omnis iste.', 'PU77823H9ANM99OGB57T081J041U61', NULL, 1837520715, 'Đồ gia dụng', '00000000-0000-0000-0000-000000000000', 'Miyoko Mckinney', '2012-06-02 17:57:52', '2020-03-21 07:18:03'),
('1ded3dd7-32db-5bc9-9190-67245e8b283e', 'Đồng hồ ', 'DH1', 0, 3, 82, 50000, 1, 0, 'Numquam nemo omnis quas aut. Qui et non harum deleniti? Sint eveniet ut maxime omnis. Velit libero qui in rem. Similique tempora praesentium quas quis? Rem aliquam consequatur placeat et. Unde repellendus delectus id corporis. Omnis sapiente atque voluptas fuga. Suscipit et inventore earum dolore!\r\nAlias dolorum error distinctio eos.', '2BU14OD317TT5WHV8M158VLMMMR9CMQ45V07C276386A8QFR84AX9VZ977W7P3MJF68W4CGXAQ5KUB5', NULL, 829697213, 'Đồng hồ ', '00000000-0000-0000-0000-000000000000', 'Gayle Baugh', '1999-01-01 00:01:23', '1970-01-01 00:57:34'),
('1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'Giày ', 'G2', 0, 4, 610409718, 79835408, 2, 0, 'Totam facilis similique possimus natus; excepturi sit praesentium quasi similique. Commodi sunt placeat cupiditate quisquam? Recusandae rerum at explicabo qui! Cupiditate magni iure et rem. Iusto corrupti dolorem aliquid voluptatem. Magnam adipisci pariatur sed ut. Ut numquam doloremque velit temporibus. Est illo reprehenderit ea quos! Ipsa ratione error est natus.', 'S7U1LCSGK2CH698W937ISU648FJ9AGBQ7GY16Y4', NULL, 307297988, 'Giày ', '00000000-0000-0000-0000-000000000000', 'Adah Jameson', '2017-10-01 16:44:23', '1971-07-31 11:21:05'),
('24629593-3d34-32fd-997d-e8c757976496', 'Váy', 'V1', 1, 13, 97, 6000000, 1, 1, 'Quaerat neque quae qui non; beatae culpa molestiae nulla quibusdam? Ipsa nobis quia voluptatibus consequatur; repellendus adipisci sint quod ad. Consectetur voluptatem sed delectus consequatur; nihil molestiae iusto quas eum. Quis nesciunt dolorem earum est! Dolorem porro magnam ut quo; laborum dolorem totam ut adipisci.\r\nIpsum ullam nobis ratione a.\r\n', 'KBOCNBS', NULL, 614948849, 'Váy', '00000000-0000-0000-0000-000000000000', 'Melia Gates', '1999-01-01 00:01:38', '1971-06-17 07:53:58'),
('284ccb05-337b-7e6f-9090-67245e8b283e', 'Váy', 'V2', 0, 13, 941, 4500000, 1, 1, 'Natus nulla nemo error alias. Laborum ut sit quas aut. Possimus voluptate temporibus quidem et! Consequatur aut doloribus aut reprehenderit. Ut suscipit repellat obcaecati dolorum! Voluptates sit accusamus beatae quia? Asperiores repellat ut ullam ipsam! Assumenda magnam sed quibusdam quasi; assumenda iusto fugit error rerum? Eligendi et laudantium perspiciatis aliquid.\r\n', '0P0ZB1RJ8X54', 'PrincetonOrange', 829697212, 'Váy/ Váy', '24629593-3d34-32fd-997d-e8c757976496', 'Adam Maddox', '1999-01-01 00:15:42', '1978-06-16 09:25:41'),
('2bbbd485-6df2-536a-7e32-6a1673ffca7c', 'Hoa quả ', 'HG2', 0, 9, 375725662, 70938980, 3, 0, 'Molestias voluptatem quia id est. Laborum dolores aut expedita consequatur! Ut minima maiores iste facilis. Tenetur ipsam nihil facere sit. Vel ut error corrupti illum. Ut omnis ex aliquid rem. Possimus nam sequi nesciunt repellat!\r\nQui voluptas nesciunt cupiditate error. Quae temporibus odit fuga laboriosam! Optio sit optio voluptates quis.', '942NUFQ6TVQV3', 'BabyBlueEyes', 614948845, 'Hoa quả / Hoa quả ', '11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Stanford Sullivan', '1999-12-10 18:46:25', '1989-01-23 14:23:18'),
('2dcedb9c-6c32-7d27-977d-e8c757976496', 'Đồ dùng cá nhân', 'DDCN1', 0, 1, 338493263, 240000, 1, 0, 'Animi minus architecto soluta accusamus dolore fugit dolore sunt quod. Veritatis eaque sit fugiat similique. Natus asperiores omnis ratione et blanditiis officiis id accusantium ducimus minima doloremque labore dicta consequatur. Quo distinctio et labore voluptates; dicta temporibus et quaerat et. Maxime iusto sed excepturi error; sed fuga animi voluptatem non.', '4M46S3B', NULL, 1043326479, 'Đồ dùng cá nhân', '00000000-0000-0000-0000-000000000000', 'Ariel Hermann', '2002-10-01 22:27:30', '1970-01-01 00:00:25'),
('2fb0b105-7808-503a-76dd-867949feb8b5', 'Nước ngọt ', 'NN2', 0, 11, 982959394, 6000, 4, 0, 'Ducimus consequuntur quidem inventore dolore. Voluptas reiciendis ut in consectetur; et omnis ducimus nihil nesciunt. Nihil nobis id sit perspiciatis. Molestias illum eos similique itaque. In aut modi sit eligendi.\r\nQuasi asperiores nihil sequi et. Omnis voluptatem enim et perspiciatis! Mollitia ex qui voluptas ut. Id sit cumque qui dolores.', 'Q4T', NULL, 2052269079, 'Nước ngọt ', '00000000-0000-0000-0000-000000000000', 'Josephine Norwood', '2006-07-26 20:16:17', '1980-06-23 18:27:10'),
('3599ef50-13ed-5404-0e63-eeb1d8ed8cef', 'Đồ dùng cá nhân', 'DDCN2', 1, 1, 87, 100000, 1, 1, 'Quod dolor adipisci earum et; laboriosam voluptatem placeat nam aut; perferendis iste qui nesciunt asperiores. Eos quia natus quisquam ipsum. Nihil distinctio autem veniam culpa? Qui aut odit sit aliquam. Architecto excepturi alias repellendus saepe! Sit explicabo maxime nemo harum; laborum unde earum non at. Eos beatae perspiciatis error voluptatum;\r\n', '8VP26X', 'BabyPink', 614948848, 'Đồ dùng cá nhân/ Đồ dùng cá nhân', '2dcedb9c-6c32-7d27-977d-e8c757976496', 'Elli Robertson', '1999-01-01 00:01:28', '2014-07-30 23:18:58'),
('3760d71f-6e2f-5b32-19cb-6694bdaf6128', 'Giày da', 'GD1', 1, 6, 220000, 330000, 2, 1, 'Giày da phong cách', NULL, 'đen', 24562, 'Giày / Giày da', '1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'vtt', '2021-03-17 16:48:39', '2021-03-17 16:48:39'),
('404fe340-1fd3-414b-aadb-e5d54223c257', 'Giày vải', 'G3', 0, 8, 404512240, 8000, 2, 1, 'Eaque doloribus dicta corporis omnis accusamus vitae non. Magnam a hic similique fugiat! Animi quia eos non omnis; inventore et eius sit et; et corporis ipsam quos culpa. Unde magni fugit recusandae laudantium. Earum maiores eos magnam aut! Enim quo qui aliquam quibusdam? Ut aut odit ipsum error; numquam ratione et tempore corrupti.', 'GU2G0MM4OAUQI06ISX316J6DST11Y7VRR35IZ0FQ9K621K9846QJ2TYK', 'PrussianBlue', 1417748997, 'Giày / Giày vải', '1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'Delcie Abney', '2003-01-06 17:04:13', '1970-01-01 02:09:09'),
('4577565a-7e3e-493a-74dd-867949feb8b5', 'Quần ', 'Q1', 1, 12, 137654331, 180000, 1, 0, 'Dicta inventore voluptatem dicta deserunt. Voluptatem voluptate asperiores consectetur blanditiis. Consequuntur dolorem quo et necessitatibus! Dolor minima amet adipisci sed. Temporibus perspiciatis unde quia maxime; quia dolores minima reprehenderit tenetur. Quia maxime et sit sed; perspiciatis quam sunt iure veritatis. Voluptas accusamus voluptatibus omnis corrupti. Exercitationem quia ut;', 'C75Z7903Q1P3RMQK', NULL, 1632497362, 'Quần ', '00000000-0000-0000-0000-000000000000', 'Felix Alba', '2007-01-17 16:42:08', '2018-10-07 19:37:35'),
('469b3ece-744a-45d5-957d-e8c757976496', 'Đồ dùng học tập', 'DDCN3', 0, 1, 826968319, 68725912, 1, 0, 'Et blanditiis minima ut odit id hic consequatur omnis quidem fugit minima. Iste et esse in laborum consectetur ut et vel molestiae quis architecto vel temporibus? Debitis molestias natus esse delectus. Est odio earum voluptatem eligendi obcaecati ab unde similique omnis voluptatem sit nisi ipsum suscipit.', '0', NULL, 307297986, 'Đồ dùng học tập', '00000000-0000-0000-0000-000000000000', 'Vanita Kelleher', '2013-07-11 20:51:56', '2020-04-09 14:21:38'),
('4760d61f-6e2f-5b32-19cb-66948daf6128', 'Khăn bông', 'KB1', 1, 10, 250000, 300000, 1, 1, NULL, NULL, 'đen', 1702, 'Khăn/ Khăn bông', '4760d71f-6e2f-5b32-19cb-66948daf6128', 'vtt', '2021-03-17 23:39:35', '2021-03-17 23:39:35'),
('4760d71f-6e2f-5b32-19cb-66948daf6128', 'Khăn', 'K1', 0, 10, 515483199, 63000, 1, 1, 'Esse perferendis dolor distinctio voluptas commodi consequatur sint consequatur adipisci voluptate voluptatem magnam error similique. Ut est velit accusantium sint laboriosam tempora et sunt similique iste, voluptatem ratione exercitationem! Omnis quo omnis commodi hic nesciunt magnam iure error iste perspiciatis ut iste quam. Voluptas ratione exercitationem perspiciatis ut; itaque est sit.', 'ROW2DRZ2005J', NULL, 829697211, 'Khăn', '00000000-0000-0000-0000-000000000000', 'Nathan Salisbury', '2007-04-25 08:42:04', '1970-01-01 00:10:39'),
('4760d71f-6e2f-5b32-19cb-6694bdaf6128', 'Khăn quàng cổ', 'kqc1', 1, 10, 20000, 30000, 1, 1, 'khăn quàng cổ học sinh', NULL, 'đen', 4562, 'Khăn/ Khăn quàng cổ', '4760d71f-6e2f-5b32-19cb-66948daf6128', 'vtt', '2021-03-17 15:53:57', '2021-03-17 15:53:57'),
('4cb513ea-dfad-4c96-8902-37808fba484f', 'Áo', 'A1', 1, 15, 500000, 600000, 2, 1, 'string', 'string', 'string', 1899, NULL, '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-19 23:30:13', '2021-03-19 23:30:13'),
('4d7b21db-2e02-12b7-a9db-e5d54223c257', 'Nước ngọt ', 'NN3', 1, 11, 513577678, 9000, 4, 1, 'Et voluptate, voluptatem fugit tenetur omnis tenetur dolorum rerum obcaecati magnam dolor laudantium dolor dolore.', '5D5K8HVZ764159Q1SU2117L42R0WF736HUY36OKBNTNBR0DTY', 'OxfordBlue', 614948847, 'Nước ngọt / Nước ngọt ', '2fb0b105-7808-503a-76dd-867949feb8b5', 'Winnifred Brantley', '2006-12-10 05:22:26', '1999-10-21 05:42:49'),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Giày ', 'G4', 0, 4, 847685069, 20000, 2, 0, 'Quia quidem mollitia dolore sint. Accusamus rerum iste voluptatem facilis. Temporibus voluptatem quia quis ratione. Quas officia dolores nihil maxime! Quaerat et omnis labore molestiae. Possimus ea nam animi laboriosam! Eos rem sed animi consequatur. Placeat perspiciatis et consectetur voluptatem. Dolorem delectus quo corporis suscipit. Fugit incidunt saepe vel nostrum!', 'J6O39DFL85', NULL, 92549621, 'Giày ', '00000000-0000-0000-0000-000000000000', 'Marcos Abraham', '2006-01-04 04:58:33', '1970-01-01 00:00:08'),
('5608f456-3b97-2e05-5d92-08c864661f9c', 'Nước ngọt ', 'NN4', 1, 11, 312, 15000, 4, 1, 'Velit ut eaque voluptas eveniet nulla et sit aut ut voluptate rerum quia. Odit natus omnis voluptatem consequatur et excepturi rerum nisi et illum! Voluptatem magnam maxime ducimus minima consectetur. Dolor iusto tempora, ut natus perspiciatis laborum totam beatae cumque exercitationem tempore minus pariatur necessitatibus.', 'A3T642GTLZ', NULL, 1258074845, 'Nước ngọt ', '00000000-0000-0000-0000-000000000000', 'Jerome Gipson', '1999-01-01 00:05:13', '1970-01-01 00:00:10'),
('5660d465-6020-48f3-75dd-867949feb8b5', 'Giày sneaker', 'G5', 0, 7, 446434411, 337797849, 2, 0, 'Vitae sequi sit ab soluta. Iste ut est id dolorum. Qui quis odio qui dolorum. Perspiciatis omnis nihil sit necessitatibus! Blanditiis qui nobis dolor vel. Dolorem error autem sint facilis! Libero aut illo exercitationem nam. Non facere recusandae et tempora. Qui eveniet omnis qui vel. Eveniet et quia saepe omnis.\r\n', '75I922893D25Z', 'Crimson', 2052269078, 'Giày / Giày vải/ Giày sneaker', '404fe340-1fd3-414b-aadb-e5d54223c257', 'Laura Barger', '2011-05-23 17:42:46', '2007-12-24 13:40:16'),
('59d19422-6657-452e-a7db-e5d54223c257', 'Đồ dùng học tập', 'DDCN4', 0, 1, 63, 727689123, 1, 1, 'Laboriosam ut est porro sed. Voluptatem veritatis reiciendis iusto dicta. Doloribus distinctio perspiciatis autem velit! Enim saepe ex natus magnam; neque molestiae magnam aut voluptatem. Omnis nesciunt nostrum aut in. Dolore iste unde vel veritatis! Et cupiditate sunt omnis eligendi.\r\nNeque commodi modi blanditiis fugit. Amet vel assumenda enim velit!\r\n', 'R011HR8810360F607A', 'Cream', 92549622, 'Đồ dùng học tập/ Đồ dùng học tập', '469b3ece-744a-45d5-957d-e8c757976496', 'Denisha Mcginnis', '1999-01-01 00:01:04', '1978-08-30 04:07:51'),
('5ae2d70b-201d-3e23-7f32-6a1673ffca7c', 'Xe máy', 'XM1', 0, 14, 184601663, 20000000, 1, 1, 'Molestiae perspiciatis dicta nisi ut. Est expedita voluptas natus quam. Explicabo magni consequatur sed enim. In quia ut numquam ea? Numquam voluptates soluta natus facilis. Tempora perferendis blanditiis laudantium culpa? Suscipit quia voluptas iste consectetur! Fugiat sed est aut iste. Et expedita ut voluptas qui. Et unde voluptatum nostrum ut;\r\n', '5812N66M598N', NULL, 1837520717, 'Xe máy', '00000000-0000-0000-0000-000000000000', 'Gertie Abel', '2016-12-22 09:47:13', '1970-01-01 02:25:46'),
('5b2fcdf5-2050-7cb2-8f90-67245e8b283e', 'Giày bata', 'G6', 0, 5, 4, 33000, 2, 1, 'Facilis amet enim nihil enim. Sunt ab ut quo debitis; dolore aut quia rem aut. Unde quae architecto sed expedita! Autem qui vitae neque ut. Non rerum quisquam iusto et; sunt unde nostrum adipisci voluptatem. Quo laudantium odit sint expedita. Et eum nisi rerum quia. Dolores aspernatur veritatis placeat quasi.\r\n', '0YK98Y0TCG9S67X89G0N4C5YM0I6K31V0688', 'Cardinal', 1837520716, 'Giày / Giày bata', '1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'Burton Bunnell', '1999-01-01 00:00:05', '1970-01-01 00:56:40'),
('5e024ca3-a4f5-46ea-9757-701bce8dded7', 'Áo mưa', 'AM1', 1, 15, 500000, 600000, 2, 1, 'string', 'string', 'string', 18991, NULL, '00000000-0000-0000-0000-000000000000', 'vtt', '2021-03-19 23:35:54', '2021-03-19 23:35:54'),
('6764ab86-6fcc-2757-8032-6a1673ffca7c', 'Đồng hồ ', 'DH2', 0, 3, 810259606, 235568205, 1, 1, 'Dolore voluptatem ut voluptas ab sunt. Quia dolore rem eaque, consequatur aut error ut atque eos quidem et blanditiis. Ut iure id nam rerum placeat corporis quia adipisci. Cum aut ut, aliquid sed unde a qui earum ipsa sit laudantium perferendis aspernatur. Et itaque iste aut quibusdam perspiciatis.', '7313WR1OKMJ45Q6KE3KZ4D', NULL, 307297989, 'Đồng hồ ', '00000000-0000-0000-0000-000000000000', 'Lilla Perez', '2012-05-28 23:15:32', '1974-05-14 02:00:43'),
('68478414-705a-2626-5c92-08c864661f9c', 'Quần ', 'Q1', 0, 12, 0, 70000, 1, 0, 'Ratione est error non ut. Vel sit possimus numquam nesciunt. Doloribus sed quisquam molestias ut! Aut est error reiciendis animi. Nihil provident amet incidunt sit. Veritatis et vero amet qui. Impedit qui et modi iste? Fugit natus esse est a. Dolorem ut dolor sit provident; eum dolorem necessitatibus minus et.', 'NXVP6U', NULL, 614948846, 'Quần ', '00000000-0000-0000-0000-000000000000', 'Adam Geer', '1999-01-01 00:00:01', '1970-01-01 00:01:06'),
('6916f8cf-1279-16d8-9290-67245e8b283e', 'Váy', 'V3', 0, 13, 286972919, 350000, 1, 0, 'Veritatis quae nisi ut consectetur. Veniam inventore sit dolore dicta! Odit eveniet repellendus quae voluptatum. Odit architecto possimus non unde? Accusamus eveniet tempore tempora at! Perspiciatis unde et non et; inventore nisi consectetur quidem illo. Perferendis totam sunt sed qui. Assumenda itaque autem quis id? Similique voluptatem et sunt itaque!\r\n', 'B046O7645NUV53LFNZ952E622N1WXI7GM39AMP50M', NULL, 829697214, 'Váy', '00000000-0000-0000-0000-000000000000', 'Curtis Hutson', '2018-07-13 04:50:49', '2013-11-16 23:38:21'),
('7623d42f-35f4-1ce5-987d-e8c757976496', 'Xe máy', 'XM2', 0, 14, 3815037, 60000000, 1, 1, 'Quis voluptas mollitia fuga qui. Quasi molestiae est assumenda vero. Sed consequatur nesciunt alias neque. Perspiciatis magni sit eaque hic. Voluptate id itaque nemo quia; unde doloribus sed laudantium repudiandae. Aspernatur et dolores ad et? Corporis eius natus voluptates eum. Et sit quidem molestiae veniam. Praesentium cupiditate qui eveniet ut.\r\n', 'QJG099D79P747Y00T217LY27NO02E3WI5741', 'LavenderPurple', 92549623, 'Xe máy/ Xe máy', '5ae2d70b-201d-3e23-7f32-6a1673ffca7c', 'Myles Angel', '2019-09-06 15:11:02', '1985-01-08 09:48:14'),
('7686595d-16d5-33b3-0080-e8e2a817c80e', 'Váy', 'V4', 0, 13, 202255179, 600000, 1, 0, 'Fuga et quos voluptatibus natus. Dolore enim quae et sed! Sunt optio magni exercitationem nam. Quia doloremque eligendi sint est.\r\nDelectus reprehenderit tempora commodi neque. Repellat sit qui dolore voluptatem; rem ut beatae id atque. Ipsam perspiciatis quibusdam consequatur non! Non consequatur soluta sit voluptates. Qui libero corrupti vel sed.', '1N721N62J', NULL, 1043326478, 'Váy', '00000000-0000-0000-0000-000000000000', 'Eusebia Noland', '2003-10-18 03:50:22', '1993-10-01 06:15:57'),
('768f8e64-7d10-20c9-967d-e8c757976496', 'Giày ', 'G7', 1, 4, 332201870, 460734547, 2, 0, 'Omnis dicta aut non ut. Deserunt et velit sed hic! Est voluptatem fugit est totam. Sit nihil autem distinctio est! Voluptatem ea molestiae voluptatem magni. Quibusdam sit aut consequatur itaque. Sint corporis nam reiciendis dolore! Ut enim voluptatem unde non. Tenetur sint autem et adipisci.\r\nQuia qui obcaecati tempore dignissimos.', '2H321E6XU287N8G8H7379871K9B7192931C56ZADG818DQ16QY1OU1GE6YL0K5B08', NULL, 2052269077, 'Giày ', '00000000-0000-0000-0000-000000000000', 'Oma Lawler', '2019-11-27 20:16:29', '1977-05-07 10:50:28'),
('7bec5682-21c4-666f-a8db-e5d54223c257', 'Váy', 'V5', 1, 13, 486269949, 400000, 1, 0, 'Et quaerat consectetur veniam itaque non labore est quam. Deserunt ullam aspernatur voluptates error est ut cumque mollitia laborum ipsum; modi laboriosam enim quidem dolorem commodi et error quam tempora deleniti. Eius quasi numquam dicta voluptatem quo qui et rerum soluta adipisci est in aut vero. Dolorem enim voluptatem aspernatur omnis.', 'L3M2L2CE68XAU3V20D14NWAPL04NYT69A6008VA8N54161HNA0WS7Q9UI25M73LS9PY', 'DogwoodRose', 1258074844, 'Váy/ Váy', '6916f8cf-1279-16d8-9290-67245e8b283e', 'Freeman Selby', '2010-07-09 12:08:06', '1970-01-01 00:06:55');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;